name: springboot-playground
services:
  postgresql:
    image: postgres:18.0
    hostname: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: no
    ports:
      - "5432:5432"
